added save manager and super basic save data class
nshooter3/HarmonyQuest pull request #10
Opened 2019-10-30 07:56 UTC by nshooter3

Added savemanager for initializing, saving, and loading save files. The save file itself is handled via a serializable save data class, allowing us to track new parameters simply by adding them to the file. Due to this setup, we can reference save params by name through intellisense when changing them. When the game is a saved or loaded, the current instance of the SaveData class and its parameters are converted to or from binary.

Possible issues include support for old save files if we patch the game to add new parameters, though this may be a problem better addressed once the game is further along.

2019-10-31 03:53 UTC, mitjmcc requested changes
Looks good and simple.
Two things though:
- Might as well add a game version int/string. It'll help with updates and is a simple thing to include now to get us started.
- Some error handling around the file I/O? Some try/catch statements would do. We can decide what to actually do in the catch statements later

2019-11-04 02:06 UTC, mitjmcc approved these changes

2019-11-05 02:43 UTC, Matthew-DeLong approved these changes
My three comments are actually one comment, but I'm happy with this as-is. It looks very easy to add to the SaveData, so I'm not worried about trying get everything we need in it right away.

2019-11-05 02:43 UTC, Matthew-DeLong commented on Assets/Scripts/Saving/SaveDataManager.cs
> +                Debug.LogError("Error saving file " + fileNum + "\n" + e.Message + "\n" + e.StackTrace);
We should actually have some kind of error handling here. Maybe the return type to a bool and leave it to whatever is calling this function?

2019-11-05 02:43 UTC, Matthew-DeLong commented on Assets/Scripts/Saving/SaveDataManager.cs
> +                Debug.LogError("Error initializing file " + fileNum + "\n" + e.Message + "\n" + e.StackTrace);
We should actually have some kind of error handling here. Maybe the return type to a bool and leave it to whatever is calling this function?

2019-11-05 02:43 UTC, Matthew-DeLong commented on Assets/Scripts/Saving/SaveDataManager.cs
> +                Debug.LogError("Error loading file " + fileNum + "\n" + e.Message + "\n" + e.StackTrace);
We should actually have some kind of error handling here. Maybe the return type to a bool and leave it to whatever is calling this function?

2019-11-07 04:53 UTC, nshooter3 commented
SaveDataManager now returns a bool and has an out parameter for the error message instead of throwing an exception.

2019-11-08 02:19 UTC, Matthew-DeLong approved these changes

2019-11-08 05:08 UTC, merged