Pathfinding
nshooter3/HarmonyQuest pull request #9
Opened 2019-10-24 07:43 UTC by nshooter3

Implemented our first navmesh to allow for pathfinding in our probuilder environments.

Implemented three layers of AI scripts as a starting point for our enemies.

* NavMeshTraveler: Top level AI class. Only handles the generation of navmesh paths between the agent and its destination.
* AggroableEnemy: Mid level AI class. Handles the tracking and transition of AI states for a generic enemy, such as aggroing and chasing the player. This is separated from NavMeshTraveler in case we come up with a different type of enemy that uses different AI states.
* BasicNavMeshEnemy: Bottom level base implementation of a generic enemy. This agent will use the states determined by AggroableEnemy to actually move the enemy and make it do specific things.

Added a static navmesh util class to make some helpful functions readily available.

2019-10-31 04:20 UTC, mitjmcc commented
I got this error by dashing a whole bunch, specifically behind the box in the bottom right of the test scene:
```
InvalidOperationException: Queue empty.
System.Collections.Generic.Queue`1[T].ThrowForEmptyQueue () (at <c9226b2f33b7421e85bb391f94075e49>:0)
System.Collections.Generic.Queue`1[T].Dequeue () (at <c9226b2f33b7421e85bb391f94075e49>:0)
GameAI.NavMeshTraveler.GeneratePathToTarget () (at Assets/Scripts/GameAI/NavMeshTraveler.cs:98)
GameAI.NavMeshTraveler.CheckIfPathNeedsToBeRegenerated () (at Assets/Scripts/GameAI/NavMeshTraveler.cs:78)
GameAI.NavMeshTraveler.Update () (at Assets/Scripts/GameAI/NavMeshTraveler.cs:65)
GameAI.AggroableEnemy.Update () (at Assets/Scripts/GameAI/AggroableEnemy.cs:67)
GameAI.BasicNavMeshEnemy.Update () (at Assets/Scripts/GameAI/BasicNavMeshEnemy.cs:58)
```

I might be moving off the Nav Mesh

2019-10-31 04:34 UTC, mitjmcc requested changes
General game feel notes:
- Base speed is real fast, so it's constantly bumping you
- You can eliminate a lot of the jitteriness of the AI movement by setting the `Interpolate` of the AI's `Rigidbody` to `Interpolate`.

2019-10-31 04:34 UTC, mitjmcc commented on Assets/Scripts/GameAI/BasicNavMeshEnemy.cs
> +                navPos.transform.position = new Vector3(aggroTarget.transform.position.x, aggroTarget.transform.position.y + 2.25f, aggroTarget.transform.position.z);
Is that a 2.25f magic number I see?

2019-11-04 02:22 UTC, mitjmcc approved these changes
Looks and plays good

2019-11-05 05:21 UTC, Matthew-DeLong requested changes
The NavMeshTraveler and NavMeshUtil classes I really, really like. They're setting up a nice, solid foundation for all AI's pathfinding needs. 

AggroableEnemy and BasicNavMeshEnemy I have a few structural issues with. The crux of this that I think AI traits like "Aggroable" and "Will hunt you down like the scum you are" ought be be handled via composition instead of inheritance. Ideally, we'd be able to drop the aggroable script on a particularly fearsome potted plant and have it try to attack Melody if she comes near, then later on we can decide that it has legs now throw a "NavMesh" script on the enemy, and have it chase her down.

2019-11-05 05:21 UTC, Matthew-DeLong commented on Assets/Scripts/GameAI/NavMeshTraveler.cs
> +        private float pathRefreshTimer = 0;
We might be able to save fractions of a nanosecond if you make this 0f

2019-11-05 05:21 UTC, Matthew-DeLong commented on Assets/Scripts/GameAI/NavMeshTraveler.cs
> +        private float pathRefreshRate = 0.5f;
I think we should keep an eye on all these config variables. I think they'll probable end up as static variables. My gut feeling is that our lives will be simpler and better if all the AI is ticking at the same time. Otherwise, it's probably going to get unwieldy once there a few different enemies.

2019-11-05 05:21 UTC, Matthew-DeLong commented on Assets/Scripts/GameAI/NavMeshUtil.cs
> +                return -1;
-1.0f***

Goodness man! The precious fractional nanoseconds wasted casting! Honestly, C# may handle this at compile time, but it won't hurt.

2019-11-05 05:21 UTC, Matthew-DeLong commented on Assets/Scripts/GameAI/AggroableEnemy.cs
> +        public CollisionWrapper aggroZone;
This opens up a neat possibility of having the enemy aggro based on a hitbox that isn't centered on the enemy itself. I like it.

2019-11-05 05:21 UTC, Matthew-DeLong commented on Assets/Scripts/GameAI/AggroableEnemy.cs
> +        /// A Transform stuck to the bottom of our navigation agent. This ensures that the agent's position on the navmesh is tracked by a position that actually touches the navmesh.
This is fine as-is, but just as a thought, would it be a better idea to shoot a ray down on start and create the navigation transform where it hits the ground?

2019-11-06 04:59 UTC, nshooter3 commented on Assets/Scripts/GameAI/NavMeshTraveler.cs
> +        private float pathRefreshRate = 0.5f;
Think I might just hold off on tweaking this until the next PR, where I will add the enemy group handling logic. Noted, though.

2019-11-06 05:04 UTC, nshooter3 commented on Assets/Scripts/GameAI/AggroableEnemy.cs
> +        /// A Transform stuck to the bottom of our navigation agent. This ensures that the agent's position on the navmesh is tracked by a position that actually touches the navmesh.
I misunderstood your suggestion when we talked about this earlier, will give it a shot and see how it works. Would be a good solution for pathfinding for an enemy falling off of something.

2019-11-06 05:10 UTC, nshooter3 commented on Assets/Scripts/GameAI/NavMeshUtil.cs
> +                return -1;
Fixed

2019-11-06 05:10 UTC, nshooter3 commented on Assets/Scripts/GameAI/NavMeshTraveler.cs
> +        private float pathRefreshTimer = 0;
Fixed

2019-11-06 08:56 UTC, nshooter3 commented on Assets/Scripts/GameAI/AggroableEnemy.cs
> +        /// A Transform stuck to the bottom of our navigation agent. This ensures that the agent's position on the navmesh is tracked by a position that actually touches the navmesh.
Adjusted navmesh agent behavior to raycast downward to the mesh if they are airborne. This is a proof of concept implementation, which is a bit sloppy and doesn't account for airborne navigation targets. It works, though. I will hold off on implementing a more elegant version of it until my first AI refactor.

2019-11-07 04:14 UTC, nshooter3 commented
I've fixed all smaller requests and bugs that were pointed out. I agree with Matthew's points about redoing the structure, however that will be addressed in a separate PR for the sake of keeping things moving.

2019-11-07 04:15 UTC, merged